// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R4Clothes.Shared.Models;

namespace R4ClothesAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("R4Clothes.Shared.Models.ChiTietHoaDon", b =>
                {
                    b.Property<int>("MaChiTietHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int>("Mahoadon")
                        .HasColumnType("int");

                    b.Property<int>("Masanpham")
                        .HasColumnType("int");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<string>("Tensanpham")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("MaChiTietHoaDon");

                    b.HasIndex("Mahoadon");

                    b.HasIndex("Masanpham");

                    b.ToTable("ChiTietHoaDons");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.ChiaSe", b =>
                {
                    b.Property<int>("MaChiaSe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("int");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChiaSe");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaSanPham");

                    b.ToTable("ChiaSes");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.DanhGiaSanPham", b =>
                {
                    b.Property<int>("MaDanhGiaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Makhachhang")
                        .HasColumnType("int");

                    b.Property<int>("Masanpham")
                        .HasColumnType("int");

                    b.Property<string>("Noidung")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Thoigian")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDanhGiaSanPham");

                    b.HasIndex("Makhachhang");

                    b.HasIndex("Masanpham");

                    b.ToTable("DanhGiaSanPhams");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.HoaDon", b =>
                {
                    b.Property<int>("Mahoadon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Makhachhang")
                        .HasColumnType("int");

                    b.Property<DateTime>("Ngaydat")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nguoiquantri")
                        .HasColumnType("int");

                    b.Property<double>("Tongtien")
                        .HasColumnType("float");

                    b.Property<int>("Trangthai")
                        .HasColumnType("int");

                    b.HasKey("Mahoadon");

                    b.HasIndex("Makhachhang");

                    b.HasIndex("Nguoiquantri");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.KhachHang", b =>
                {
                    b.Property<int>("Makhachhang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Gioitinh")
                        .HasColumnType("int");

                    b.Property<string>("Hinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matkhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Ngaysinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sodienthoai")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Tenkhachhang")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Makhachhang");

                    b.ToTable("KhachHangs");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.LoaiSanPham", b =>
                {
                    b.Property<int>("Maloai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Tenloai")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Maloai");

                    b.ToTable("LoaiSanPhams");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.QuanTri", b =>
                {
                    b.Property<int>("Maquantri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Hoten")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Matkhau")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Taikhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Maquantri");

                    b.ToTable("QuanTris");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.SanPham", b =>
                {
                    b.Property<int>("Masanpham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Dacbiet")
                        .HasColumnType("bit");

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int?>("Giamgia")
                        .HasColumnType("int");

                    b.Property<string>("Hinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Maloai")
                        .HasColumnType("int");

                    b.Property<int>("Maquantri")
                        .HasColumnType("int");

                    b.Property<string>("Mota")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("Ngaynhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.Property<int>("Soluotxem")
                        .HasColumnType("int");

                    b.Property<string>("Tensanpham")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Trangthai")
                        .HasColumnType("bit");

                    b.HasKey("Masanpham");

                    b.HasIndex("Maloai");

                    b.HasIndex("Maquantri");

                    b.ToTable("SanPhams");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.YeuThich", b =>
                {
                    b.Property<int>("Mayeuthich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Makhachhang")
                        .HasColumnType("int");

                    b.Property<int>("Masanpham")
                        .HasColumnType("int");

                    b.HasKey("Mayeuthich");

                    b.HasIndex("Makhachhang");

                    b.HasIndex("Masanpham");

                    b.ToTable("YeuThichs");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.ChiTietHoaDon", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.HoaDon", "HoaDon")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("Mahoadon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R4Clothes.Shared.Models.SanPham", "SanPham")
                        .WithMany("ChiTietHoaDons")
                        .HasForeignKey("Masanpham")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.ChiaSe", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R4Clothes.Shared.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.DanhGiaSanPham", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("Makhachhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R4Clothes.Shared.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("Masanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.HoaDon", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("Makhachhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R4Clothes.Shared.Models.QuanTri", "QuanTri")
                        .WithMany()
                        .HasForeignKey("Nguoiquantri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("QuanTri");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.SanPham", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.LoaiSanPham", "LoaiSanPhams")
                        .WithMany("SanPhams")
                        .HasForeignKey("Maloai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R4Clothes.Shared.Models.QuanTri", "QuanTris")
                        .WithMany()
                        .HasForeignKey("Maquantri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiSanPhams");

                    b.Navigation("QuanTris");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.YeuThich", b =>
                {
                    b.HasOne("R4Clothes.Shared.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("Makhachhang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("R4Clothes.Shared.Models.SanPham", "SanPham")
                        .WithMany()
                        .HasForeignKey("Masanpham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.HoaDon", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.LoaiSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("R4Clothes.Shared.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietHoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
